[package]
name = "advent-2023-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indoc = "2.0.4"
itertools = "0.12.0"
lazy_static = "1.4.0"
regex = "1.9.5"

[dev-dependencies]
rstest = "0.18.2"
