[package]
name = "advent-2022-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "lib"

[dependencies]
lazy_static = "1.4.0"
regex = "1.9.5"
